---
title: "YACHT"
author: "Stephen Noell"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE, 
                      warning = FALSE,
                      fig.align = "center",
                      fig.width = 10,
                      fig.height = 6)
```


```{r Libraries and seed}

# Libraries
library("tidyverse")       # data wrangling and visualisation
library("svglite") #for saving SVGs
library("ggpubr") #for saving plots
library("here")            # set the path to the folder 
library("RColorBrewer")
library("reshape2")
library("tidyr")
library("readxl")
library("readr")

set.seed(57)
```

```{r}
#########Get data in from YACHT

files <- list.files(pattern = "\\yacht.xlsx$")

# Read the first sheet of each file, add a filename column, and combine
# Note that first sheet is results of min_coverage of 1, which is standard
# also note that YACHT is using ANI of >95%, which is species threshold. So these are same species.
df_comb <- bind_rows(lapply(files, function(file) {
  df <- read_excel(file, sheet = 1)  # Read first sheet
  df$acc <- gsub("_dein_mags_yacht\\.xlsx$", "", file)  # Clean filename
  return(df)
}))

df_comb2 <- as.data.frame(df_comb) %>%
  dplyr::rename(MAG = organism_name) %>%
  dplyr::filter(in_sample_est == TRUE) %>%
  dplyr::select(MAG, acc)

#Now import data from branchwater
branch <-  read.csv("deinoc_97_cani.csv") %>%
  dplyr::select(MAG, acc)

#compare the two
match <- inner_join(branch, df_comb2, by = c("acc", "MAG"))
nrow(branch)
nrow(match)

#in yacht but not branch
ya_no_br <- anti_join(df_comb2, branch, by = c("acc", "MAG"))
nrow(ya_no_br)

#all branchwater hits are confirmed by YACHT for these Deinococcota MAGs.
#YACHT picked up four additional hits that branchwater didn't, all four are TR_bin7 in Kergeulen Island metagenomes (so not that surprising)

df_comb3 <- as.data.frame(df_comb)
#write.csv(df_comb3, "Table_S2_yacht.csv")
```
