---
title: "Temp plotting"
author: "Stephen Noell"
date: "26/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE, 
                      warning = FALSE,
                      fig.align = "center",
                      fig.width = 10,
                      fig.height = 6)
```


```{r}

# Libraries
library("tidyverse")       # data wrangling and visualisation
library("here")            # set the path to the folder
library("ggplot2")
library("ggpubr") #for putting figs together
library("RColorBrewer") #for color palettes
library("svglite") #for saving SVGs
library("reshape2")
library(lubridate)
library(patchwork)

set.seed(57)
```

```{r}
# Shared color scale limits
shared_limits <- c(-50, 75)

# Shared theme
shared_theme <- theme_bw() +
  theme(
    axis.text.x = element_text(size = 8, angle = 45, hjust = 1),
    axis.text.y = element_text(size = 7),
    axis.ticks = element_line(),
    axis.title.y = element_blank(),
    strip.text.y.left = element_text(angle = 0),
    strip.placement = "outside",
    strip.background = element_blank(),
    legend.position = "right",
    panel.spacing = unit(0.4, "lines")
  )

# Shared color scale
shared_color <- scale_color_gradient2(
  low = "darkblue", high = "darkred", mid = "white",
  midpoint = 0, limits = shared_limits,
  name = "Temp (C)"
)

###########
# WC 2019
###########
temp_data <- read.csv("wc_2019_temp_data.csv", header = TRUE) %>%
  dplyr::select(-weeks, -1, -hours, -days) %>%
  dplyr::rename("100 cm" = 2, "70 cm" = 3, "40 cm" = 4, "10 cm" = 5)

temp_data_m <- melt(temp_data, measure.vars = 2:5)
temp_data_m$value <- ifelse(temp_data_m$value < -75 | temp_data_m$value > 75, NA, temp_data_m$value)
temp_data_m$Date.time <- parse_date_time(temp_data_m$Date.time,
                                          orders = c("mdy IMS p", "mdy HMS"), tz = "UTC")

wc19_xlimits <- as.POSIXct(c(min(temp_data_m$Date.time), max(temp_data_m$Date.time)), tz = "UTC")
wc19_xbreaks <- seq(wc19_xlimits[1], wc19_xlimits[2], by = "60 days")

wc2019 <- ggplot(temp_data_m, aes(x = Date.time, y = value, color = value)) +
  geom_line() +
  labs(x = "Date") +
  scale_x_datetime(limits = wc19_xlimits, breaks = wc19_xbreaks, date_labels = "%b %Y") +
  scale_y_continuous(breaks = seq(-50, 70, by = 20)) +
  shared_color +
  shared_theme +
  facet_wrap(~factor(variable, levels = c('10 cm', '40 cm', '70 cm', '100 cm')),
             ncol = 1, strip.position = "left")

###########
# Helper function for 2023-2025 data
###########
load_sensor_data <- function(filepath) {
  data <- read.csv(filepath, stringsAsFactors = FALSE)
  data$Sensor25 <- gsub(";", "", data$Sensor25)
  data <- data %>%
    mutate(across(starts_with("Sensor"), as.numeric))
  
  data_long <- data %>%
    pivot_longer(cols = starts_with("Sensor"),
                 names_to = "Sensor",
                 values_to = "SensorValue")
  
  data_long$Sensor <- factor(data_long$Sensor, levels = paste0("Sensor", 1:25))
  data_long$SensorValue <- ifelse(data_long$SensorValue < -75 | data_long$SensorValue > 75,
                                   NA, data_long$SensorValue)
  
  sensor_labels <- data.frame(
    Sensor = paste0("Sensor", 16:25),
    Label = c("TempLogger", "0 cm", "20 cm", "40 cm", "60 cm",
              "80 cm", "100 cm", "120 cm", "140 cm", "160 cm")
  )
  
  data_long <- data_long %>%
    left_join(sensor_labels, by = "Sensor") %>%
    filter(!is.na(Label), Label != "TempLogger")
  
  data_long$Label <- factor(data_long$Label,
                             levels = c("0 cm", "20 cm", "40 cm", "60 cm",
                                        "80 cm", "100 cm", "120 cm", "140 cm", "160 cm"))
  
  data_long$timestamp <- as.POSIXct(data_long$timestamp, origin = "1970-01-01", tz = "UTC")
  
  return(data_long)
}

make_plot <- function(data, y_breaks = seq(-50, 70, by = 20)) {
  x_limits <- as.POSIXct(c(min(data$timestamp), max(data$timestamp)), tz = "UTC")
  x_breaks <- seq(x_limits[1], x_limits[2], by = "30 days")
  
  ggplot(data, aes(x = timestamp, y = SensorValue, color = SensorValue)) +
    geom_line() +
    labs(x = "Date") +
    scale_x_datetime(limits = x_limits, breaks = x_breaks, date_labels = "%b %Y") +
    scale_y_continuous(breaks = y_breaks) +
    shared_color +
    shared_theme +
    facet_wrap(~ Label, ncol = 1, strip.position = "left")
}

###########
# WC 2023-2024
###########
wc23_data <- load_sensor_data("wc_2023_2024_temp_data.csv")
wc23 <- make_plot(wc23_data)

###########
# TR 2023-2024
###########
tr23_data <- load_sensor_data("tr_2023_2024_temp_data.csv")
tr23 <- make_plot(tr23_data, y_breaks = seq(-55, 75, by = 20))

###########
# TR 2024-2025
###########
tr24_data <- load_sensor_data("tr_2024_2025_temp_data.csv")
tr24 <- make_plot(tr24_data, y_breaks = seq(-55, 75, by = 20))

###########
# Combine
###########
# Combine with fixed heights and labels
wc2019_padded <- plot_spacer() / wc2019 / plot_spacer() +
  plot_layout(heights = c(1, 2, 1))

all <- wrap_plots(wc2019_padded, wc23, tr23, tr24, nrow = 1) +
  plot_layout(guides = "collect", widths = c(0.7, 1, 0.5, 1.5)) +
  plot_annotation(tag_levels = "A") &
  theme(legend.position = "bottom",
        legend.direction = "horizontal")

#ggsave("../Figure S1_temp.png", all, width = 400, height = 200, units = "mm", dpi = 300)
#ggsave("../Figure S1_temp.svg", all, width = 400, height = 200, units = "mm", dpi = 300)

```